name: build

on:
  push:
    branches:
      - main

jobs:
  editable-install:
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'windows-2022'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        pip install .[dev]
    - name: Install editable
      run: |
        pip install --no-build-isolation --config-settings=editable-verbose=true -Cbuild-dir=".build_editable" --editable .
    - name: Import a module
      run: |
        python -c "from rs_example_lib import frf"

  build-wheel:
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'windows-2022'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        pip install .[build]
    - name: Build wheel
      run: |
        python -m build .
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel_${{ matrix.os }}
        path: dist/

  install-wheel:
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'windows-2022'
    runs-on: ${{ matrix.os }}
    needs: build-wheel
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        pip install numpy
    - name: Download wheel
      uses: actions/download-artifact@v4
      with:
        name: wheel_${{ matrix.os }}
        path: dist/
    - name: Install wheel
      shell: bash
      run: |
        pip install dist/rs_example_lib*.whl
    - name: Import a module
      run: |
        python -c "from rs_example_lib import frf"
